### ISSUE TITLE
The code doesn't work

### ISSUE THREAD

**Issue by GENESIS-PLUS** [semmelsamu/router#4]
I put it as you have in the instructions, but it does not display anything on the main page. php 8.1

include("controller/router.php");
$router = new \semmelsamu\Router();
$router->add("/", function() { echo "Hello!"; }); 
echo $router->route();

**Comment by semmelsamu** [comment]
Try
`$router->add("", function() { echo "Hello!"; });`
You don't need the slash (`/`).

Hope it works now!

I also updated the README accordingly. Thank You!
